---

- name: Download minio client
  become: true
  get_url:
    # Downloads the latest client, can't find a way to download a particular
    # version
    url:
      https://dl.min.io/client/mc/release/linux-amd64/archive/mc.RELEASE.2020-08-08T02-33-58Z
    checksum:
      sha256:81993b7cec9cbf2809d83c612bde833eb19dae16e128e3466227eee70f3293b7
    dest: /usr/local/bin/mc
    mode: u=rwx,g=rx,o=rx

- name: Copy minio-user.sh
  become: true
  template:
    src: minio-user.sh
    dest: /usr/local/bin/minio-user.sh
    mode: u=rwx,g=rx,o=rx

- name: Create config directories
  become: true
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - /etc/minio-s3-gateway
    - /root/.mc

- name: Copy policy-readwrite-subdir.json.template
  become: true
  copy:
    src: policy-readwrite-subdir.json.template
    dest: /etc/minio-s3-gateway/policy-readwrite-subdir.json.template
    mode: 0644

- name: Create placeholder text file
  become: true
  copy:
    content: "{{ minio_s3_gateway_placeholder_content }}"
    dest: /etc/minio-s3-gateway/README.txt
    mode: 0644

- name: Create root mc config
  become: true
  template:
    src: mc-config-json.j2
    dest: /root/.mc/config.json
    backup: true
    mode: u=r,g=,o=

# Needed so that it appears in the sudo PATH
- name: Symlink minio client and script to /usr/bin
  become: true
  file:
    path: /usr/bin/{{ item }}
    src: /usr/local/bin/{{ item }}
    state: link
  loop:
    - mc
    - minio-user.sh
