---
# Install Docker and trigger all restart handlers
- name: Converge
  hosts: all
  roles:
    - role: ome.docker


# Install this role
- name: Converge
  hosts: all

  pre_tasks:

    - name: Workaround to get host IP inside docker
      shell: hostname -I | cut -d' ' -f1
      register: hostname_ip
      check_mode: false
      changed_when: false
      tags:
        # Ignore [306] Shells that use pipes should set the pipefail option
        - skip_ansible_lint

  roles:

    - role: ome.minio_s3_gateway
      minio_s3_gateway_remote_endpoint: "http://{{ hostname_ip.stdout }}:12345"
      minio_s3_gateway_access_key: remote-access
      minio_s3_gateway_secret_key: remote-secret
